config/routes.rb
Rails.application.routes.draw do
  namespace :core, path:'/' do

    root to:'dashboard#dashboard'
    get 'calendar', to:'dashboard#calendar'
    delete 'destroy_activities', to:'dashboard#destroy_activities'
    resources :tasks, class_name:'Core::Task', except:[:show]
    resources :notes, class_name:'Core::Note'

    devise_for :users, class_name:'Core::User', module: :devise, skip:[:registrations]

    resources :users, class_name:'Core::User', except:[:destroy] do
      get 'send_invite', on: :member
      get 'lookup', on: :collection
    end
  end

  namespace :crm, path: '/sales' do

    resources :accounts, class_name:'Crm::Account' do
      get 'lookup', on: :collection
    end

    resources :contacts, class_name:'Crm::Contact' do
      get 'lookup', on: :collection
    end

    resources :leads, class_name:'Crm::Lead' do
      get 'lookup', on: :collection
      post 'clone', on: :member
      post 'convert', on: :member
    end

    resources :deals, class_name:'Crm::Deal' do
      get 'lookup', on: :collection
    end
  end

  get 'home', to: 'home#index'
end

app/models/concerns/core/noteable.rb
module Core::Noteable
  extend ActiveSupport::Concern

  included do
    has_many :notes, dependent: :destroy, as: :noteable, class_name:'Core::Note'
    accepts_nested_attributes_for :notes,  allow_destroy: true
  end

end

app/models/concerns/core/personable.rb
module Core::Personable
  extend ActiveSupport::Concern
  included do
    has_one :person, dependent: :destroy, as: :personable, class_name:'Core::Person'
    accepts_nested_attributes_for :person,  allow_destroy: true
  end
end

app/models/concerns/core/taskable.rb
module Core::Taskable
  extend ActiveSupport::Concern
  included do
    has_many :tasks, dependent: :destroy, as: :taskable, class_name:'Core::Task'
    accepts_nested_attributes_for :tasks, allow_destroy: true
  end
end

app/models/core.rb
module Core
  def self.table_name_prefix
    'core_'
  end
end

app/models/core/note.rb
class Core::Note < ApplicationRecord
  extend FriendlyId
  friendly_id :uid, use: :slugged

  belongs_to :noteable, polymorphic: true, optional: true
  belongs_to  :created_by, class_name:'Core::User'

  attr_accessor :related_to
end

app/models/core/person.rb
class Core::Person < ApplicationRecord
  extend FriendlyId

  friendly_id :uid, use: :slugged
  belongs_to :personable, polymorphic: true, optional: true

  validates_presence_of :first_name, :last_name

  def full_name
    if self.first_name && self.last_name
      "#{self.first_name} #{self.last_name}"
    else
      ""
    end
  end
end

app/models/core/task.rb
class Core::Task < ApplicationRecord
  extend FriendlyId

  friendly_id :uid, use: :slugged

  belongs_to :taskable, polymorphic: true, optional: true
  belongs_to :assigned_to, class_name:'Core::User'

  enum status:    [:not_started, :in_progress, :completed, :waiting, :deferred], _suffix: true
  enum priority:  [:high, :normal, :low], _suffix: true

  attr_accessor :related_to, :assigned_to_name

  before_validation :set_assigned_to_name

  validates_presence_of :subject, :status, :priority
  after_initialize :set_default_status, :set_default_priority, :set_random_color, if: :new_record?

  private
  def set_default_status
    self.status ||= :not_started
  end

  def set_default_priority
    self.status ||= :normal
  end

  def set_assigned_to_name
    self.assigned_to_name = self.assigned_to.person.full_name if self.assigned_to
  end

  def set_random_color
    self.color = colors.sample if self.color.nil?
  end

  def colors
    %w( #F44336 #E91E63 #9C27B0 #673AB7 #3F51B5 #2196F3 #03A9F4 #00BCD4 #009688
        #4CAF50 #8BC34A #CDDC39 #FFEB3B #FFC107 #FF9800 #FF5722 #795548 #9E9E9E
        #607D8B
      )
    end
end

app/models/core/user.rb
class Core::User < ApplicationRecord
  include Core::Personable
  extend FriendlyId

  friendly_id :uid, use: :slugged

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role:  [:user, :admin, :account_owner]

  validates :authentication_token, uniqueness: true
  before_save :ensure_authentication_token!

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def ensure_authentication_token!
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  def reset_authentication_token!
    self.authentication_token = generate_authentication_token
  end

  private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless Core::User.where(authentication_token: token).first
    end
  end
end

app/controllers/core/dashboard_controller.rb
class Core::DashboardController < ApplicationController

  # GET /dashboard
  def dashboard
    @activities = PublicActivity::Activity.includes(:owner, :trackable).order(created_at: :desc).page(params[:activity_page]).per(5)
    @deals_by_stage = Crm::Deal.by_stage
    @deal_amount_expected = Crm::Deal.amount_v_expected
    @deal_funnel = Crm::Deal.funnel_chart
  end

  # GET /dashboard
  def calendar
  end

  # DELETE /destroy_activities
  def destroy_activities
    @activities = PublicActivity::Activity.where(owner: current_user)
    @activities.destroy_all
    redirect_to core_root_path
  end
end

app/controllers/core/notes_controller.rb
class Core::NotesController < ApplicationController
  before_action :set_note, only:[:edit, :show, :update, :destroy]

  # GET /notes/new
  def new
    @note = Core::Note.new(created_by: current_core_user)
    authorize @note
  end

  # GET /notes/:id/edit
  def edit
    authorize @note
    if @note.noteable
      if @note.noteable_type.constantize.reflect_on_association(:person).respond_to?(:name)
        @note.related_to = @note.noteable.person.full_name
      elsif @note.noteable.attribute_names.include?("name")
        @note.related_to = @note.noteable.name
      end
    end
  end

  # GET /notes/:id
  def show
    authorize @note
  end

  # POST /notes
  def create
    @note = Core::Note.new(params_without_virtual_attributes)
    @note.created_by = current_core_user
    authorize @note
    @note.noteable_id = polymorphic_builder(note_params[:related_to], note_params[:noteable_type], note_params[:noteable_id])
    if @note.valid?
      @note.save
      redirect_to core_root_path
    else
      render :new
    end

  end

  # PATCH /notes/:id
  # PUT /notes/:id
  def update
    authorize @note
    @note.attributes = params_without_virtual_attributes
    @note.noteable_id = polymorphic_builder(note_params[:related_to], note_params[:noteable_type], note_params[:noteable_id])
    if @note.valid?
      @note.save
      redirect_to core_root_path
    else
      render :edit
    end
  end

  # DELETE /projects/:id
  def destroy
    authorize @note
    if @note.destroy
      redirect_back fallback_location: core_root_path
    end
  end

  private

  def set_note
    @note = Core::Note.includes(:noteable).friendly.find(params[:id])
  end

  def note_params
    params.require(:core_note).permit(
      :private, :title, :body, :noteable_type, :noteable_id, :related_to
    )
  end

  def params_without_virtual_attributes
    note_params.select do |p|
      p.exclude?('noteable_id') and p.exclude?('related_to')
    end
  end
end

app/controllers/core/tasks_controller.rb
class Core::TasksController < ApplicationController
  before_action :set_task, only:[:edit, :show, :update, :destroy]

  # GET /tasks
  def index
    if current_core_user
      @tasks = Core::Task.where(assigned_to: current_core_user).page(params[:task_page]).per(5)
    else
      @tasks = Core::Task.page(params[:task_page]).per(5)
    end
  end

  # GET /tasks/new
  def new
    @task = Core::Task.new
    authorize @task
    @task.assigned_to = current_core_user
    @task.assigned_to_name = current_core_user.person.full_name
  end

  # GET /tasks/:id/edit
  def edit
    authorize @task
    @task.assigned_to_name = @task.assigned_to.person.full_name if @task.assigned_to
    if @task.taskable
      if @task.taskable_type.constantize.reflect_on_association(:person).respond_to?(:name)
        @task.related_to = @task.taskable.person.full_name
      elsif @task.taskable.attribute_names.include?("name")
        @task.related_to = @task.taskable.name
      end
    end
  end

  # POST /tasks
  def create
    @task = Core::Task.new(params_without_virtual_attributes)
    authorize @task
    if !task_params[:assigned_to_name].blank? && task_params[:assigned_to_id].blank?
      @user = Core::User.joins(:person).where('core_people.first_name Like :name OR core_people.last_name LIKE :name', name:task_params[:assigned_to_name]).first
      @task.assigned_to = @user if @user
    else
      @task.assigned_to_id = task_params[:assigned_to_id]
    end

    @task.taskable_id = polymorphic_builder(task_params[:related_to], task_params[:taskable_type], task_params[:taskable_id])

    if @task.valid?
      @task.save
      flash[:success] = t('controllers.core/tasks.create.success')
      redirect_to core_calendar_path
    else
      render :new
    end
  end

  # PATCH /tasks/:id
  # PUT /tasks/:id
  def update
    authorize @task
    @task.attributes = params_without_virtual_attributes
    if !task_params[:assigned_to_name].blank? && task_params[:assigned_to_id].blank?
      @user = Core::User.joins(:person).where('core_people.first_name Like :name OR core_people.last_name LIKE :name', name:task_params[:assigned_to_name]).first
      @task.assigned_to = @user if @user
    else
      @task.assigned_to_id = task_params[:assigned_to_id]
    end

    @task.taskable_id = polymorphic_builder(task_params[:related_to], task_params[:taskable_type], task_params[:taskable_id])

    if @task.valid?
      @task.save
      flash[:success] = t('controllers.core/tasks.update.success')
      redirect_to core_calendar_path
    else
      render :edit
    end
  end

  # DELETE /projects/:id
  def destroy
    authorize @task
    if @task.destroy
      flash[:success] = t('controllers.core/tasks.destroy.success')
      redirect_to core_tasks_path
    end
  end

  private
  def set_task
    @task = Core::Task.includes(:assigned_to, :taskable).friendly.find(params[:id])
  end

  def task_params
    params.require(:core_task).permit(
      :assigned_to_id, :taskable_type, :taskable_id,
      :status, :subject, :description, :priority, :location,
      :starts_at, :ends_at, :assigned_to, :assigned_to_name, :related_to,
    )
  end

  def params_without_virtual_attributes
    task_params.select do |p|
      p.exclude?('taskable_id') and
      p.exclude?('related_to') and
      p.exclude?('assigned_to_name') and
      p.exclude?('assigned_to_id') and
      p.exclude?('assigned_to')
    end
  end
end

app/controllers/core/users_controller.rb
class Core::UsersController < ApplicationController
  before_action :set_user, only:[:edit, :show, :update, :send_invite]
  # GET /users
  def index
    respond_to do |format|
      format.html
      format.json { render json: Core::UserDatatable.new(view_context) }
    end
  end

  #TODO: Implement this on an api controller with user - api token authentication
  def lookup
    respond_to do |format|
      format.json { render json: Core::UserLookup.new(view_context) }
    end
  end

  # GET /users/new
  def new
    @user = Core::User.new
    @user.build_person
    authorize @user
  end

  # GET /users/:id/edit
  def edit
    authorize @user
  end

  # GET /users/:id/
  def show
    authorize @user
    redirect_to core_edit_user_path(@user) if @user.person == nil
  end

  # GET /users/:id/send_invite
  def send_invite
    @user.invite!(current_core_user)
    redirect_to core_user_path(@user)
  end

  # POST /users
  def create
    @user = Core::User.new(user_params)
    authorize @user
    @user.password = SecureRandom.hex(5)
    @user.password_confirmation = @user.password

    if @user.valid?
      @user.skip_confirmation!
      @user.skip_invitation= true
      @user.save
      redirect_to core_user_path(@user)
    else
      render :new
    end
  end

  # PATCH /users/:id
  # PUT /users/:id
  def update
    authorize @user
    if @user.update_attributes(user_params)
      redirect_to core_user_path(@user)
    else
      render :edit
    end
  end

  private
  def set_user
    @user = Core::User.friendly.find(params[:id])
  end

  def user_params
    params.require(:core_user).permit(
      :username, :nickname, :company,
      :department, :division, :start_of_day, :end_of_day,
      :email, :password, :role_id,

      person_attributes:
        [:_destroy, :id, :title, :first_name, :last_name, :phone, :home_phone,
          :other_phone, :email, :assistant, :asst_phone, :extension, :mobile,
          :birthdate
        ]
    )
  end
end

app/views/core/tasks/_form.html.haml
-content_for :javascripts do
  = javascript_include_tag 'lib/lookup'

= form_for @task, html:{class:'form-horizontal'} do |f|
  .row
    .col-sm-6
      = form_group_for f, :subject do
        .col-sm-8
          .input-line
            = f.text_field :subject, class:'form-control'
    .col-sm-6
      = form_group_for f, :status do
        .col-sm-8
          .input-line
            = options_for_t_enum(f, :status)
  .row
    .col-sm-6
      = form_group_for f, :assigned_to do
        .col-sm-8
          .input-group
            %span.input-group-btn
              %a.btn.btn-default{data:{toggle:'modal', target:'#userLookup'}}
                %i.fa.fa-search
            = f.hidden_field :assigned_to_id, id:'assigned_to_input'
            = f.text_field :assigned_to_name, id:'assigned_to_label', class:'form-control'
    .col-sm-6
      = form_group_for f, :related_to do
        .col-sm-8
          .input-group
            %span.input-group-bt
              = select_for_lookup(f, :taskable_type)
              = f.hidden_field :taskable_id, value:"", id:'taskable_id_input'
            .input-group-btn
              %a.btn.btn-default#relatedToBtn{data:{toggle:'modal', target:'#accountsLookup'}}
                %i.fa.fa-search
            = f.text_field :related_to, id:'related_to_label', class:'form-control'
  .row
    .col-sm-6
      = form_group_for f, :starts_at do
        .col-sm-8
          .input-line
            = f.datetime_field :starts_at, class:'form-control'
    .col-sm-6
      = form_group_for f, :ends_at do
        .col-sm-8
          .input-line
            = f.datetime_field :ends_at, class:'form-control'
  .row
    .col-sm-6
      = form_group_for f, :priority do
        .col-sm-8
          .input-line
            = options_for_t_enum(f, :priority)
    .col-sm-6
      = form_group_for f, :location do
        .col-sm-8
          .input-line
            = f.text_field :location, class:'form-control'
  .row
    .col-sm-6
      = form_group_for f, :description do
        .col-sm-8
          .input-line
            = f.text_area :description, class:'form-control'
  .row
    .form-group
      .text-center.col-sm-12
        = f.submit t('views.shared.save'), class: 'btn btn-sm btn-primary'
        = link_to t('views.shared.cancel'), :back, class: 'btn btn-sm btn-danger'

app/views/core/tasks/_lookup.html.haml
= modal(t('views.core/users.lookup.title'), lookup_core_users_path(format: :json), [t('activerecord.attributes.core/person.full_name'), t('activerecord.attributes.core/user.email')], 'userLookup','assigned_to_input', 'assigned_to_label', 'usersDatatable')
= modal(t('views.crm/leads.lookup.title'), lookup_crm_leads_path(format: :json), [t('activerecord.attributes.crm/lead.number'), t('activerecord.attributes.core/person.full_name'), t('activerecord.attributes.crm/lead.company') ], 'leadsLookup','taskable_id_input', 'related_to_label', 'leadsDatatable')
= modal(t('views.crm/accounts.lookup.title'), lookup_crm_accounts_path(format: :json), [t('activerecord.attributes.crm/account.number'), t('activerecord.attributes.crm/account.name'), t('activerecord.attributes.crm/account.email') ], 'accountsLookup','taskable_id_input', 'related_to_label', 'accountsDatatable')
= modal(t('views.crm/contacts.lookup.title'), lookup_crm_contacts_path(format: :json), [t('activerecord.attributes.crm/contact.number'), t('activerecord.attributes.core/person.first_name'), t('activerecord.attributes.core/person.last_name'), t('activerecord.attributes.core/person.email') ], 'contactsLookup','taskable_id_input', 'related_to_label', 'contactsDatatable')
= modal(t('views.crm/deals.lookup.title'), lookup_crm_deals_path(format: :json), [t('activerecord.attributes.crm/deal.number'), t('activerecord.attributes.crm/deal.name') ], 'dealsLookup','taskable_id_input', 'related_to_label', 'dealsDatatable')

app/views/core/tasks/_task.html.haml
- tasks.each do |task|
  %tr
    %td
      = link_to t('views.shared.edit'), edit_core_task_path(task)
      |
      = link_to t('views.shared.delete'), core_task_path(task), method: :delete, data:{confirm: t('views.shared.delete_message')}
    %td= link_to task.assigned_to.person.full_name, task.assigned_to
    %td= task.subject
    %td= task.description
    %td= l(task.starts_at, format: :short) if task.starts_at
    %td= l(task.ends_at, format: :short) if task.ends_at

app/views/core/tasks/_tasks_widget.html.haml
#task-card.card
  .card-header
    %p.lead= t('views.core/tasks.index.title')
    .card-actions
      = link_to new_core_task_path, class:'btn btn-default' do
        %i.fa.fa-plus
  .card-block
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th
          %th=t('activerecord.attributes.core/task.assigned_to')
          %th=t('activerecord.attributes.core/task.subject')
          %th=t('activerecord.attributes.core/task.description')
          %th=t('activerecord.attributes.core/task.starts_at')
          %th=t('activerecord.attributes.core/task.ends_at')
      %tbody#tasks
        = render 'core/tasks/task', tasks: tasks
    #taskPaginator= paginate @tasks, remote: true, param_name: :task_page

app/views/core/tasks/edit.html.haml
.card
  .card-header
    %p.lead= @task.subject
  .card-block
    = render 'form'
    = render 'lookup'

app/views/core/tasks/index.html.haml
= render 'core/tasks/tasks_widget', tasks: @tasks

app/views/core/tasks/index.js.haml
$('#tasks').html('#{escape_javascript render("core/tasks/task", tasks: @tasks)}');
$('#taskPaginator').html("#{escape_javascript(paginate(@tasks, remote: true, param_name: :task_page))}");

app/views/core/tasks/new.html.haml
.card
  .card-header
    %p.lead= t('views.core/tasks.new.title')
  .card-block
    = render 'form'
    = render 'lookup'