config/routes.rb
Rails.application.routes.draw do
  namespace :core, path:'/' do

    root to:'dashboard#dashboard'
    get 'calendar', to:'dashboard#calendar'
    delete 'destroy_activities', to:'dashboard#destroy_activities'
    resources :tasks, class_name:'Core::Task', except:[:show]
    resources :notes, class_name:'Core::Note'

    devise_for :users, class_name:'Core::User', module: :devise, skip:[:registrations]

    resources :users, class_name:'Core::User', except:[:destroy] do
      get 'send_invite', on: :member
      get 'lookup', on: :collection
    end
  end

  namespace :crm, path: '/sales' do

    resources :accounts, class_name:'Crm::Account' do
      get 'lookup', on: :collection
    end

    resources :contacts, class_name:'Crm::Contact' do
      get 'lookup', on: :collection
    end

    resources :leads, class_name:'Crm::Lead' do
      get 'lookup', on: :collection
      post 'clone', on: :member
      post 'convert', on: :member
    end

    resources :deals, class_name:'Crm::Deal' do
      get 'lookup', on: :collection
    end
  end

  get 'home', to: 'home#index'
end

app/models/crm.rb
module Crm
  def self.table_name_prefix
    'crm_'
  end
end

app/models/crm/account.rb
class Crm::Account < ApplicationRecord
  include PublicActivity::Model
  include Core::Noteable
  include Core::Taskable
  extend FriendlyId

  tracked only:[:create, :update], owner: :set_tracked_owner
  before_destroy :remove_activity

  friendly_id :uid, use: :slugged

  belongs_to :created_by, class_name:'Core::User'

  has_many :contacts, class_name:'Crm::Contact'
  has_many :deals, class_name:'Crm::Deal'

  validates_presence_of :name, :number
  validates_uniqueness_of :number

  after_initialize :set_defaults, if: :new_record?

  enum rating:    [:hot, :warm, :cold], _suffix: true
  enum ownership: [:public, :private, :subsidiary, :other], _suffix: true
  enum priority:  [:high, :low, :medium], _suffix: true
  enum employees: [:large, :medium, :small, :micro], _suffix: true

  private

  def set_defaults
    self.number     ||= "A-" + generate_number
    self.rating     ||= :warm
    self.ownership  ||= :private
    self.priority   ||= :medium
    self.employees  ||= :micro
  end

  def generate_number
    loop do
      token = rand(1000).to_s
      break token unless Crm::Account.where(number: token).first
    end
  end

  def set_tracked_owner
    self.created_by
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.create")
    activity.destroy if activity.present?
    true
  end
end

app/models/crm/contact.rb
class Crm::Contact < ApplicationRecord
  include PublicActivity::Model
  include Core::Noteable
  include Core::Personable
  include Core::Taskable
  extend FriendlyId

  tracked only:[:create, :update], owner: :set_tracked_owner
  before_destroy :remove_activity

  friendly_id :uid, use: :slugged

  belongs_to :created_by, class_name:'Core::User'
  belongs_to :account, class_name:'Crm::Account', optional: true

  enum level: [:primary, :secondary, :tertiary], _suffix: true
  enum lead_source: [:web, :phone, :referral, :purchased_list, :other], _suffix: true

  attr_accessor :account_label
  before_validation :set_account_label
  validates_presence_of :person, :number
  validates_uniqueness_of :number

  after_initialize :set_defaults, if: :new_record?

  private

  def set_account_label
    self.account_label = self.account.name if self.account
  end

  def set_defaults
    self.number       ||= "C-" + generate_number
    self.level        ||= :primary
    self.lead_source  ||= :web
  end

  def generate_number
    loop do
      token = rand(1000).to_s
      break token unless Crm::Contact.where(number: token).first
    end
  end

  def set_tracked_owner
    self.created_by
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.create")
    activity.destroy if activity.present?
    true
  end
end

app/models/crm/lead.rb
class Crm::Lead < ApplicationRecord
  include PublicActivity::Model
  include Core::Personable
  include Core::Noteable
  include Core::Taskable
  extend FriendlyId

  friendly_id :uid, use: :slugged

  tracked only:[:create, :update], owner: :set_tracked_owner
  before_destroy :remove_activity

  belongs_to :created_by, class_name:'Core::User'

  validates_presence_of :company, :status, :number
  validates_uniqueness_of :number
  after_initialize :set_defaults, if: :new_record?

  enum rating:    [:hot, :warm, :cold], _suffix: true
  enum status:    [:open, :working, :closed, :lost], _suffix: true

  def clone_with_associations
    new_lead = self.dup
    new_lead.build_person(self.person.dup.attributes)
    new_lead.number = "L-" + generate_number
    new_lead
  end

  private
  def set_defaults
    self.number     ||= "L-" + generate_number
    self.rating     ||= :warm
    self.status     ||= :open
  end

  def generate_number
    loop do
      token = rand(1000).to_s
      break token unless Crm::Lead.where(number: token).first
    end
  end

  def set_tracked_owner
    self.created_by
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.create")
    activity.destroy if activity.present?
    true
  end
end

app/controllers/crm/accounts_controller.rb
class Crm::AccountsController < ApplicationController
  before_action :set_account, only:[:edit, :show, :update, :destroy]

  # Metodo para definir la respuesta de ingresar a el modulo de indice
  def index
    respond_to do |format|
      format.html
      format.json { render json: Crm::AccountDatatable.new(view_context) }
    end
  end

  #TODO: Implement this on an api controller with user - api token authentication
  # Metodo para manejar solicitudes de busqueda de una cuenta
  def lookup
    respond_to do |format|
      format.json { render json: Crm::AccountLookup.new(view_context) }
    end
  end

  # Definicion de cuenta nueva
  def new
    @account = Crm::Account.new
    authorize @account
  end

  # Definicion de informacion a mostrar en el detalle de la cuenta
  def show
    authorize @account
    # Se muestran 5 registros por pagina de dataTable
    @deals = @account.deals.includes(:created_by).page(params[:deal_page]).per(5)
    @contacts = @account.contacts.includes(:person, :created_by).page(params[:contact_page]).per(5)
    @tasks = @account.tasks.page(params[:task_page]).per(5)
    @notes = @account.notes.page(params[:note_page]).per(5)
  end

  def edit
    authorize @account
  end

  def create
    # Preparacion de cuenta nueva
    @account = Crm::Account.new(account_params)
    # Fijar creador de cuenta como el usuario actualmente en control
    @account.created_by = current_user
    authorize @account
    if @account.valid?
      @account.save
      # Mandar notificacion a la interfaz del exito de la operacion
      flash[:success] = t('controllers.crm/accounts.create.success')
      redirect_to crm_accounts_path
    else
      render :new
    end
  end

  def update
    authorize @account
    if @account.update(account_params)
      # Mandar notificacion a la interfaz del exito de la operacion
      flash[:success] = t('controllers.crm/accounts.update.success')
      # Redirige a catalogo de cuentas
      redirect_to crm_account_path(@account)
    else
      # Refresca el formulario de actualizacion
      render :edit
    end
  end

  def destroy
    authorize @account
    @account.destroy
    # Mandar notificacion a la interfaz del exito de la operacion
    flash[:success] = t('controllers.crm/accounts.destroy.success')
    # Redirige a catalogo de cuentas
    redirect_to crm_accounts_path
  end

  private

  def set_account
    @account = Crm::Account.includes(:created_by).friendly.find(params[:id])
  end

  def account_params
    # Filtro de parametros permitidos
    params.require(:crm_account).permit(
      :name, :number, :website, :industry, :annual_revenue, :rating,
      :ownership, :priority, :employees, :locations, :sic_code, :active,
      :ticker_symbol, :description, :phone, :email, :extension
    )
  end
end

app/controllers/crm/contacts_controller.rb
class Crm::ContactsController < ApplicationController
  before_action :set_contact, only:[:edit, :show, :update, :destroy]

  # Metodo para definir la respuesta de ingresar al catalogo
  def index
    respond_to do |format|
      format.html
      format.json { render json: Crm::ContactDatatable.new(view_context) }
    end
  end

  #TODO: Implement this on an api controller with user - api token authentication
  # Metodo para manejar solicitudes de busqueda de un contacto
  def lookup
    respond_to do |format|
      format.json { render json: Crm::ContactLookup.new(view_context) }
    end
  end

  # Definicion de nuevo contacto
  def new
    @contact = Crm::Contact.new
    @contact.build_person
    authorize @contact
  end

  def edit
    authorize @contact
    @contact.account_label = @contact.account.name if @contact.account
  end

  # Definicion de informacion a mostrar en el detalle del contacto
  def show
    authorize @contact
    # Se muestran 5 registros por pagina de dataTable
    @tasks = @contact.tasks.page(params[:task_page]).per(5)
    @notes = @contact.notes.page(params[:note_page]).per(5)
  end

  def create
    # Preparacion de contacto nuevo
    @contact = Crm::Contact.new(contact_params)
    # Fijar creador de contacto como el usuario actualmente en sesion
    @contact.created_by = current_user
    authorize @contact
    # Si se dejo en blanco el numero de cuenta buscar primer coincidencia de posibles cuenta
    if !contact_params[:account_label].blank? && contact_params[:account_id].blank?
      @account = Crm::Account.where('name Like :name OR number LIKE :name', name: contact_params[:account_label]).first
      @contact.account = @account if @account
    else
      @contact.account_id = contact_params[:account_id]
    end

    if @contact.valid?
      @contact.save
      # Mandar notificacion a la interfaz del exito de la operacion
      flash[:success] = t('controllers.crm/contacts.create.success')
      redirect_to crm_contact_path(@contact)
    else
      render :new
    end
  end

  def update
    authorize @contact
    @contact.attributes = contact_params
    # If no contact is selected
    if contact_params[:account_label].blank?
      @contact.account = nil
    end

    if @contact.valid?
      @contact.save
      # Mandar notificacion a la interfaz del exito de la operacion
      flash[:success] = t('controllers.crm/contacts.update.success')
      redirect_to crm_contact_path(@contact)
    else
      # Refrescar formulario de edicion
      render :edit
    end
  end

  def destroy
    authorize @contact
    @contact.destroy
    # Mandar notificacion a la interfaz del exito de la operacion
    flash[:success] = t('controllers.crm/contacts.destroy.success')
    # Redirigir a catalogo de contactos
    redirect_to crm_contacts_path
  end

  private

  def set_contact
    @contact = Crm::Contact.includes(:person, :created_by).friendly.find(params[:id])
  end

  def contact_params
    # Filtro de parametros permitidos
    params.require(:crm_contact).permit(
      :account_label, :account_id, :description, :created_by_id, :lead_source,
      :level, :language, :number,
      person_attributes:
        [:_destroy, :id, :title, :first_name, :last_name, :phone, :home_phone,
          :other_phone, :email, :assistant, :asst_phone, :extension, :mobile,
          :birthdate
        ]
    )
  end
end

app/controllers/crm/deals_controller.rb
class Crm::DealsController < ApplicationController
  before_action :set_deal, only:[:edit, :show, :update, :destroy]

  # Metodo para definir la respuesta de ingresar al catalogo
  def index
    respond_to do |format|
      format.html
      format.json { render json: Crm::DealDatatable.new(view_context) }
    end
  end

  #TODO: Implement this on an api controller with user - api token authentication
  # Metodo para manejar solicitudes de busqueda de deal
  def lookup
    respond_to do |format|
      format.json { render json: Crm::DealLookup.new(view_context) }
    end
  end

  # Definicion de nuevo deal
  def new
    @deal = Crm::Deal.new
    authorize @deal
  end

  # Definicion de informacion a mostrar en el detalle del deal
  def show
    authorize @deal
    # Se muestran 5 registros por pagina de dataTable
    @tasks = @deal.tasks.page(params[:task_page]).per(5)
    @notes = @deal.notes.page(params[:note_page]).per(5)
  end

  def edit
    authorize @deal
    @deal.account_label = @deal.account.name if @deal.account
  end

  def create
    # Preparacion de deal nuevo
    @deal = Crm::Deal.new(deal_params)
    # Fijar creador de contacto como el usuario core actualmente en sesion
    @deal.created_by = current_core_user
    authorize @deal
    if @deal.valid?
      @deal.save
      # Mandar notificacion a la interfaz del exito de la operacion
      flash[:success] = t('controllers.crm/deals.create.success')
      # Redirigir a detalle del nuevo deal
      redirect_to crm_deal_path(@deal)
    else
      # Refrescar formulario de creacion
      render :new
    end
  end

  def update
    authorize @deal
    @deal.attributes = deal_params
    if @deal.valid?
      @deal.save
      # Mandar notificacion a la interfaz del exito de la operacion
      flash[:success] = t('controllers.crm/deals.update.success')
      redirect_to crm_deal_path(@deal)
    else
      # Refrescar formulario de edicion
      render :edit
    end
  end

  def destroy
    authorize @deal
    @deal.destroy
    # Mandar notificacion a la interfaz del exito de la operacion
    flash[:success] = t('controllers.crm/deals.destroy.success')
    redirect_to crm_deals_path
  end

  private
  def set_deal
    @deal = Crm::Deal.includes(:account, :created_by).friendly.find(params[:id])
  end

  def deal_params
    # Filtro de parametros permitidos
    params[:crm_deal].permit(
      :account_label, :account_id,
      :name, :category, :lead_source ,:tracking_number, :description,
      :amount, :expected_revenue, :close_at, :next_step, :stage,
      :main_competitor, :delivery_status, :number, :probability
    )
  end
end

app/controllers/crm/leads_controller.rb
class Crm::LeadsController < ApplicationController
  before_action :set_lead, only:[:clone, :convert, :edit, :show, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: Crm::LeadDatatable.new(view_context) }
    end
  end

  #TODO: Implement this on an api controller with user - api token authentication
  def lookup
    respond_to do |format|
      format.json { render json: Crm::LeadLookup.new(view_context) }
    end
  end

  def clone
    authorize @lead
    @new_lead = @lead.clone_with_associations
    if @new_lead.valid?
      @new_lead.save
      flash[:success] = t('controllers.crm/leads.clone.success')
      redirect_to crm_lead_path(@new_lead)
    else
      render :new
    end
  end

  def convert
    @lead.status = :working
    @lead.save
    @account = Crm::Account.new(
      name: @lead.company,
      industry: @lead.industry,
      rating: @lead.rating,
      website: @lead.website,
      description: @lead.description,
      phone: @lead.person.phone,
      extension: @lead.person.extension,
      created_by: current_core_user,
    )
    @contact = @account.contacts.build(created_by: current_core_user)
    @contact.build_person(@lead.person.dup.attributes)

    @deal = Crm::Deal.new(
      account: @account,
      name: @lead.company.to_s + " - " + Date.today.to_s,
      category: :new_customer,
      stage: :prospecting,
      close_at: Time.now + 30.days,
      created_by: current_core_user
    )
    if @account.valid? && @deal.valid?
      @deal.tasks.new(assigned_to: current_core_user, subject:"#{@deal.number} - #{@deal.name}", priority: :normal)
      @account.save
      @deal.save
      flash[:success] = t('controllers.crm/leads.convert.success')
      redirect_to crm_account_path(@account)
      #TODO: else flash error and redirect to lead path
    end
  end

  def new
    @lead = Crm::Lead.new
    @lead.build_person
    authorize @lead
  end

  def show
    authorize @lead
    @tasks = @lead.tasks.page(params[:task_page]).per(5)
    @notes = @lead.notes.page(params[:note_page]).per(5)
  end

  def edit
    authorize @lead
  end

  def create
    @lead = Crm::Lead.new(lead_params)
    @lead.created_by = current_core_user
    authorize @lead
    if @lead.valid?
      @lead.save
      flash[:success] = t('controllers.crm/leads.create.success')
      redirect_to crm_leads_path
    else
      render :new
    end
  end

  def update
    authorize @lead
    if @lead.update_attributes(lead_params)
      flash[:success] = t('controllers.crm/leads.update.success')
      redirect_to crm_lead_path(@lead)
    else
      render :edit
    end
  end

  def destroy
    authorize @lead
    @lead.destroy
    flash[:success] = t('controllers.crm/leads.destroy.success')
    redirect_to crm_leads_path
  end

  private
  def set_lead
    @lead = Crm::Lead.includes(:person, :created_by).friendly.find(params[:id])
  end

  def lead_params
    params.require(:crm_lead).permit(
      :id, :source, :company, :industry, :sic_code, :status,
      :website, :rating, :description, :created_by_id,
      :number,
      person_attributes:
        [:_destroy, :id, :title, :first_name, :last_name, :phone, :home_phone,
          :other_phone, :email, :assistant, :asst_phone, :extension, :mobile,
          :birthdate
        ]
    )
  end
end

app/views/crm/leads/_form.html.haml
= form_for @lead, html:{class:'form-horizontal'} do |f|
  .card-block
    = f.fields_for :person do |person|
      = render 'core/shared/personable_fields', f: person
    .row
      .col-sm-6
        = form_group_for f, :company do
          .col-sm-8
            = f.text_field :company, class: 'form-control'
      .col-sm-6
        = form_group_for f, :number do
          .col-sm-8
            = f.text_field :number, class: 'form-control'
    .row
      .col-sm-6
        = form_group_for f, :industry do
          .col-sm-8
            = f.text_field :industry, class: 'form-control'
      .col-sm-6
        = form_group_for f, :sic_code do
          .col-sm-8
            = f.text_field :sic_code, class: 'form-control'
    .row
      .col-sm-6
        = form_group_for f, :website do
          .col-sm-8
            = f.text_field :website, class: 'form-control'
      .col-sm-6
        = form_group_for f, :rating do
          .col-sm-8
            = options_for_t_enum(f, :rating)
    .row
      .col-sm-6
        = form_group_for f, :status do
          .col-sm-8
            = options_for_t_enum(f, :status)
      .col-sm-6
        = form_group_for f, :source do
          .col-sm-8
            = f.text_field :source, class: 'form-control'
    .row
      .col-sm-6
        = form_group_for f, :description do
          .col-sm-8
            = f.text_area :description, class: 'form-control'
    .row.form-group.text-center
      = f.submit t('views.shared.save'), class: 'btn btn-sm btn-primary'
      = link_to t('views.shared.cancel'), :back, class: 'btn btn-sm btn-danger'

app/views/crm/leads/edit.html.haml
.card
  .card-header
    %p.lead= @lead.person.first_name if @lead.person
  = render 'form'

app/views/crm/leads/index.html.haml
-content_for :javascripts do
  = javascript_include_tag 'lib/dataTables'

#lead-card.card
  .card-header
    %p.lead= t('views.crm/leads.index.title')
    .card-actions
      = link_to new_crm_lead_path, class:'btn btn-default' do
        %i.fa.fa-plus
  .card-block
    %table.table.table-striped.table-bordered.ajax-data-table{width:'100%', cellspacing:'0', data:{source: crm_leads_path(format: :json)}}
      %thead
        %tr
          %th=t('activerecord.attributes.crm/lead.number')
          %th=t('activerecord.attributes.crm/lead.company')
          %th=t('activerecord.attributes.core/person.first_name')
          %th=t('activerecord.attributes.core/person.email')
          %th=t('activerecord.attributes.crm/lead.status')
      %tbody

app/views/crm/leads/show.html.haml
.card
  .card-header
    %p.lead= @lead.person.full_name if @lead.person
    .card-actions
      = link_to new_crm_lead_path, class:'btn btn-default' do
        %i.fa.fa-plus
      = link_to edit_crm_lead_path(@lead), class:'btn btn-default' do
        %i.fa.fa-pencil
      = link_to clone_crm_lead_path(@lead), method: :post, class:'btn btn-default' do
        %i.fa.fa-copy
      = link_to convert_crm_lead_path(@lead), method: :post, class:'btn btn-default' do
        %i.fa.fa-exchange
      = link_to crm_lead_path(@lead), method: :delete, data:{confirm: t('views.shared.delete_message')}, class:'btn btn-danger' do
        %i.fa.fa-trash
  .card-block
    %table.table.table-condensed.table-striped
      %tr
        %th=t('activerecord.attributes.crm/lead.number')
        %td= @lead.number
        %th=t('activerecord.attributes.core/person.full_name')
        %td= @lead.person.full_name
      %tr
        %th=t('activerecord.attributes.crm/lead.company')
        %td= @lead.company
        %th=t('activerecord.attributes.crm/lead.website')
        %td= @lead.website
      %tr
        %th=t('activerecord.attributes.core/person.phone')
        %td= @lead.person.phone
        %th=t('activerecord.attributes.core/person.extension')
        %td= @lead.person.extension
      %tr
        %th=t('activerecord.attributes.core/person.mobile')
        %td= @lead.person.mobile
        %th=t('activerecord.attributes.crm/lead.rating')
        %td=t("activerecord.attributes.crm/lead.ratings_options.#{@lead.rating}")
      %tr
        %th=t('activerecord.attributes.core/person.email')
        %td= @lead.person.email
        %th=t('activerecord.attributes.crm/lead.source')
        %td= @lead.source
      %tr
        %th=t('activerecord.attributes.crm/lead.industry')
        %td= @lead.industry
        %th=t('activerecord.attributes.crm/lead.sic_code')
        %td= @lead.sic_code
      %tr
        %th=t('activerecord.attributes.crm/lead.status')
        %td=t("activerecord.attributes.crm/lead.statuses_options.#{@lead.status}")
        %th=t('activerecord.attributes.crm/lead.description')
        %td= @lead.description
      %tr
        %th=t('activerecord.attributes.crm/lead.created_at')
        %td= l(@lead.created_at, format: :short)
        %th=t('activerecord.attributes.crm/lead.updated_at')
        %td= l(@lead.updated_at, format: :short)
      %tr
        %th=t('activerecord.attributes.crm/lead.created_by')
        %td= link_to @lead.created_by.person.full_name, @lead.created_by if @lead.created_by && @lead.created_by.person
        %th
        %td

= render 'core/tasks/tasks_widget', tasks: @tasks
= render 'core/notes/notes_widget', notes: @notes

app/views/crm/leads/show.js.haml
$('#tasks').html('#{escape_javascript render("core/tasks/task", tasks: @tasks)}');
$('#taskPaginator').html("#{escape_javascript(paginate(@tasks, remote: true, param_name: :task_page))}");

$('#notes').html('#{escape_javascript render("core/notes/note", notes: @notes)}');
$('#notePaginator').html("#{escape_javascript(paginate(@notes, remote: true, param_name: :note_page))}");